Fix PCI slot conflict
Error: PCI: slot 1 function 0 not available for virtio-vga, in use by virtio-net-pci,id=
Fix from https://github.com/jollheef/appvm/pull/30